### ISSUE TITLE
Retrieval Deal file system error

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/dealbot#276] opened 2021-07-07 18:16 UTC
Several retrieval deals are failing with:
```
retrieval deal failed: open /shared/bafykbzacec3zpb5zbopgiaejfes5muue4y6xbb737slrg6yxtg46oomfytp5q: read-only file system
```

UUIDs of deals with this failure.
```
  '0ac6c218-62da-490f-9472-6641d27dfe37',
  'b94a53ea-c5d2-4755-aea3-b99fc1e777b0',
  '44edb332-c86d-40b7-a53b-df55dc83c15b',
  'ea781a48-fe13-4a62-8dae-4911843824f7',
  '3049180d-22e3-42ba-9f67-12c0057357eb',
  'b9131a33-ca8c-458a-99fb-f5e8b79f4345',
  'd746d110-07f3-4b28-8d39-ffb3ef9b3c49',
  'fa2d499a-ca04-46c8-8cbd-885fd4ef94f5',
  '1ee2d909-5822-4a67-b78e-b42682ffad45',
  'f9a0235a-4aa8-43bd-bc3f-06ce9c08e1d0',
  '429fa704-18fc-4fed-8def-6b59e25e1c1a',
  '0471762a-81d2-4114-82f9-3b4f2de1f4d8',
  '91f6b120-c912-4077-a875-056875e772bc',
  '69d06f99-a6c4-4ad8-b372-82084799efe2',
  'c5880c4e-7d4d-4a56-a39a-624729919746',
  '766045d2-4c41-4919-9f47-7e669cb15777',
  '76ef9175-2bd3-4bf1-ae77-7962d1adfdcc',
  'f48ce366-8704-4d81-822c-a0dd5d2c8482',
  '057bca89-b6a0-4bb9-aec0-bc4c42b0f541',
  'c6439e19-f831-4387-8476-1bb402f6ad08',
  'af5836a2-e6ee-4078-9c40-39e84a3e75f5',
  '8af2029d-7727-4718-9d8c-448f3c98b9de',
  '3135a4ca-e772-46e9-a183-3730298c8f0d',
  '4bc8b0b2-77a6-40ab-89b6-5dd33dd5b794',
  '07d799c3-f697-4d5f-934c-6de4759f56ac',
  '3c746540-0c09-464f-99e0-206b055120a1',
  '2f3a0226-f5d9-4750-9130-dd29fb0823ba',
  '88c95e5f-2391-42ea-8404-14f5ada095b3',
  '6c4476aa-288b-4b62-af87-d2b9d600ad8c',
  '96f3151a-97ff-49a6-9d7c-e089b1c39c27',
  'a900fc0e-9296-439e-8a94-6c7d98b9e016'
  ```
  
  This indicates lotus tried to write the output file when the deal was done but couldn't. Are we running out of space? Is something else the matter?

**Comment by coryschwartz** [comment] 2021-07-07 20:16
This was caused by the setting the node data directory read-only for lotus.

I removed the readOnly restriction, and I think this should be working now.
https://github.com/filecoin-project/helm-charts/pull/90

Not closing yet, should monitor to make sure this works.

**Comment by dkkapur** [comment] 2021-11-09 20:35
Closing this for now - @coryschwartz @hannahhoward please reopen if needed!

**Closed by dkkapur** 2021-11-09 20:35 UTC
